apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: hm-shop
  annotations:
    # IRSA: This annotation binds the K8s ServiceAccount to the IAM Role
    # Replace 567776770107 with your actual AWS Account ID (injected by install.sh)
    eks.amazonaws.com/role-arn: arn:aws:iam::567776770107:role/hm-shop-backend-ecr-role
  labels:
    app: backend
