apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: hm-shop
  annotations:
    # IRSA: This annotation binds the K8s ServiceAccount to the IAM Role
    # Replace <YOUR_AWS_ACCOUNT_ID> with your actual AWS Account ID (injected by Step 9)
    eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/hm-shop-backend-ecr-role
  labels:
    app: backend
