apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hm-shop
  labels:
    app: frontend
    tier: presentation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge:       1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
        tier: presentation
    spec:
      serviceAccountName: frontend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser:    1000
        runAsGroup:   1000
      containers:
        - name: frontend
          image: 567776770107.dkr.ecr.567776770107.dkr.ecr.567776770107.dkr.ecr.ap-south-1.amazonaws.com/hm-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu:    "100m"
              memory: "128Mi"
            limits:
              cpu:    "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds:       15
            timeoutSeconds:      5
            failureThreshold:    3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds:       10
            timeoutSeconds:      3
            failureThreshold:    3
