apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: hm-shop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::567776770107:role/hm-shop-frontend-ecr-role
  labels:
    app: frontend
