apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hm-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL:        https://github.com/<YOUR_USERNAME>/Three-Tier-EKS-Terraform.git
    targetRevision: main
    path:           k8s_manifests
    directory:
      recurse: true
  destination:
    server:    https://kubernetes.default.svc
    namespace: hm-shop
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration:    5s
        factor:      2
        maxDuration: 3m
